---
- hosts: ontap
  gather_facts: false
  name: Setup ONTAP
  vars:
    hostname: "{{ inventory_hostname }}"
    username: "admin"
    volname: ansibleVolume
    #vserver: vserver1
    aggr: aggr1
    policy:
      - export-svm_citi_student1-ansibleVol2
      - export-svm_citi_student1
      - ansiblePolicy
    state: present
#  vars_prompt:
#  - name: "password"
#    prompt: "Password:"
  tasks:
  - name: Create Policy
    na_ontap_export_policy:
      state: absent
      name: "{{ item }}"
      vserver: "{{ vserver }}"
      hostname: "{{ inventory_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password}}"
    connection: local
    with_items: "{{ policy }}"
    ignore_errors: yes

#  - name: Setup rules
#    na_ontap_export_policy_rule:
#      state: absent
#      policy_name: "{{ item }}"
#      vserver: "{{ vserver }}"
#      client_match: 0.0.0.0/0
#      ro_rule: any
#      rw_rule: any
#      super_user_security: any
#      hostname: "{{ hostname }}"
#      username: "{{ netapp_username }}"
#      password: "{{ netapp_password}}"
#    connection: local
#    with_items: "{{ policy }}"
#  - name: Create volume
#    na_ontap_volume:
#      state: "{{ state }}"
#      name: "{{ volname }}"
#      aggregate_name: "{{ aggr }}"
#      size: 1
#      size_unit: gb
#      policy: "{{ policy }}"
#      junction_path: "/{{ volname }}"
#      space_guarantee: "none"
#      vserver: "{{ vserver }}"
#      hostname: "{{ hostname }}"
#      username: "{{ netapp_username }}"
#      password: "{{ netapp_password}}"
#- hosts: client
#  tasks:
#  - name: Update fstab file
#    lineinfile:
#      path: /etc/fstab
#      line: "172.32.0.184:/{{ volname }} /mnt/ontap nfs defaults 0 0"
#  - name: Verify mount directory exists
#    file:
#      path: /mnt/ontap
#      state: directory
#  - name: Mount nfs export
#    mount:
#      state: "{{ state }}"
#      path: /mnt/ontap
#      src: "172.32.0.184:/{{ volname }}"
#      fstype: nfs
#
