---
- hosts: ontap
  gather_facts: false
  connection: local
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  name: Onboard SVM
  tasks:
  - name: Create SVM
    na_ontap_svm:
      state: present
      name: "{{ vserver }}"
      root_volume: "{{ vserver}}_root"
      root_volume_aggregate: aggr1
      root_volume_security_style: unix
      <<: *login
  - name: Create interface
    na_ontap_interface:
      state: present
      interface_name: "{{ vserver }}_mgmt_data_1"
      home_port: e0d
      home_node: vsim-01
      role: data
      protocols: nfs
      admin_status: up
      failover_policy: local-only
      firewall_policy: mgmt
      is_auto_revert: true
      address: "{{ address }}"
      netmask: 255.255.255.0
      vserver: "{{ vserver }}"
      <<: *login
