---
- hosts: web
  vars:
    volname:
      - "ansibleVol1"
      - "ansibleVol2"
    state: mounted

  tasks:
  - name: Update fstab file
    lineinfile:
      path: /etc/fstab
      line: "{{data_ips}}:/{{ item }} /mnt/{{ item }} nfs defaults 0 0"
    with_items: "{{ volname }}"

  - name: Verify mount directory exists
    file:
      path: "/mnt/{{ item }}"
      state: directory
    with_items: "{{ volname }}"

  - name: Mount nfs export
    mount:
      state: "{{ state }}"
      path: "/mnt/{{ item }}"
      src: "{{data_ips}}:/{{ item }}"
      fstype: nfs
    with_items: "{{ volname }}"

  - name: Show volume is mounted
    command: df -h
    register: output

  - debug: var=output.stdout
